version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    container_name: php-app
    expose:
      - "9000"  # Expose PHP-FPM port to internal Docker network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Use 8080 on the host to avoid conflict with Apache2
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: nginx-server
